//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTTFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_details
    {
        public int studRollno { get; set; }
        public string studName { get; set; }
        public string studGender { get; set; }
        public string studSubject { get; set; }
    }
}
