#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ_28Jan
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tempdb_Trupti")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_student_detail(tbl_student_detail instance);
    partial void Updatetbl_student_detail(tbl_student_detail instance);
    partial void Deletetbl_student_detail(tbl_student_detail instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["tempdb_TruptiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_student_detail> tbl_student_details
		{
			get
			{
				return this.GetTable<tbl_student_detail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_student_details")]
	public partial class tbl_student_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _studRollno;
		
		private string _studName;
		
		private string _studGender;
		
		private string _studSubject;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudRollnoChanging(int value);
    partial void OnstudRollnoChanged();
    partial void OnstudNameChanging(string value);
    partial void OnstudNameChanged();
    partial void OnstudGenderChanging(string value);
    partial void OnstudGenderChanged();
    partial void OnstudSubjectChanging(string value);
    partial void OnstudSubjectChanged();
    #endregion
		
		public tbl_student_detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studRollno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int studRollno
		{
			get
			{
				return this._studRollno;
			}
			set
			{
				if ((this._studRollno != value))
				{
					this.OnstudRollnoChanging(value);
					this.SendPropertyChanging();
					this._studRollno = value;
					this.SendPropertyChanged("studRollno");
					this.OnstudRollnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studName", DbType="VarChar(100)")]
		public string studName
		{
			get
			{
				return this._studName;
			}
			set
			{
				if ((this._studName != value))
				{
					this.OnstudNameChanging(value);
					this.SendPropertyChanging();
					this._studName = value;
					this.SendPropertyChanged("studName");
					this.OnstudNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studGender", DbType="VarChar(100)")]
		public string studGender
		{
			get
			{
				return this._studGender;
			}
			set
			{
				if ((this._studGender != value))
				{
					this.OnstudGenderChanging(value);
					this.SendPropertyChanging();
					this._studGender = value;
					this.SendPropertyChanged("studGender");
					this.OnstudGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studSubject", DbType="VarChar(150)")]
		public string studSubject
		{
			get
			{
				return this._studSubject;
			}
			set
			{
				if ((this._studSubject != value))
				{
					this.OnstudSubjectChanging(value);
					this.SendPropertyChanging();
					this._studSubject = value;
					this.SendPropertyChanged("studSubject");
					this.OnstudSubjectChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
